
package soa.services.soap.implementations;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import soa.services.soap.interfaces.ObjectFactory;
import soa.services.soap.interfaces.RegionDTOArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RegionSOAPInterface", targetNamespace = "http://Interfaces.SOAP.services.SOA/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RegionSOAPInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(partName = "return")
    public long countAvailableSpotsAtRegion(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(partName = "return")
    public long countNotAvailableSpotsAtRegion(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @return
     *     returns soa.services.soap.interfaces.RegionDTOArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public RegionDTOArray getRegions();

}
