
package spot.soa.services.soap.implementations;

import region.soa.services.soap.interfaces.ObjectFactory;
import spot.soa.services.soap.interfaces.ParkingSpotDTOArray;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ParkingSpotSOAP", targetNamespace = "http://Interfaces.SOAP.services.SOA/", serviceName="ParkingSpotSOAPService")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ParkingSpotSOAPInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns soa.services.soap.interfaces.ParkingSpotDTOArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public ParkingSpotDTOArray getParkingSpotsByStreet(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void takeSpot(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(partName = "return")
    public long countAvailableSpotsAtStreet(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns soa.services.soap.interfaces.ParkingSpotDTOArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public ParkingSpotDTOArray getParkingSpotsByRegion(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @return
     *     returns soa.services.soap.interfaces.ParkingSpotDTOArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public ParkingSpotDTOArray getParkingSpots();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    public void leaveSpot(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(partName = "return")
    public long countNotAvailableSpotsAtStreet(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
