
package region.soa.services.soap.implementations;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RegionSOAPServiceService", targetNamespace = "http://Implementations.SOAP.services.SOA/", wsdlLocation = "http://localhost:8080/MainApplication/RegionSOAPService?wsdl")
public class RegionSOAPServiceService
    extends Service
{

    private final static URL REGIONSOAPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException REGIONSOAPSERVICESERVICE_EXCEPTION;
    private final static QName REGIONSOAPSERVICESERVICE_QNAME = new QName("http://Implementations.SOAP.services.SOA/", "RegionSOAPServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/MainApplication/RegionSOAPService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGIONSOAPSERVICESERVICE_WSDL_LOCATION = url;
        REGIONSOAPSERVICESERVICE_EXCEPTION = e;
    }

    public RegionSOAPServiceService() {
        super(__getWsdlLocation(), REGIONSOAPSERVICESERVICE_QNAME);
    }

    public RegionSOAPServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGIONSOAPSERVICESERVICE_QNAME, features);
    }

    public RegionSOAPServiceService(URL wsdlLocation) {
        super(wsdlLocation, REGIONSOAPSERVICESERVICE_QNAME);
    }

    public RegionSOAPServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGIONSOAPSERVICESERVICE_QNAME, features);
    }

    public RegionSOAPServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegionSOAPServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegionSOAPInterface
     */
    @WebEndpoint(name = "RegionSOAPServicePort")
    public RegionSOAPInterface getRegionSOAPServicePort() {
        return super.getPort(new QName("http://Implementations.SOAP.services.SOA/", "RegionSOAPServicePort"), RegionSOAPInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegionSOAPInterface
     */
    @WebEndpoint(name = "RegionSOAPServicePort")
    public RegionSOAPInterface getRegionSOAPServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Implementations.SOAP.services.SOA/", "RegionSOAPServicePort"), RegionSOAPInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGIONSOAPSERVICESERVICE_EXCEPTION!= null) {
            throw REGIONSOAPSERVICESERVICE_EXCEPTION;
        }
        return REGIONSOAPSERVICESERVICE_WSDL_LOCATION;
    }

}
